sudo: required
services:
  - docker

before_install:
  - docker build -t suparera/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run suparera/react-test npm test -- --coverage

after_success:
  - docker build -t suparera/multi-client ./client
  - docker build -t suparera/multi-nginx ./nginx
  - docker build -t suparera/multi-server ./server
  - docker build -t suparera/multi-worker ./worker
  # Log in to the docker CLI, add encryption
  # retreive docker_password from env var , and pipe to docker login command
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push suparera/multi-client
  - docker push suparera/multi-nginx
  - docker push suparera/multi-server
  - docker push suparera/multi-worker