sudo: required
services:
  - docker

before_install:
  - docker build -t suparera/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run suparera/react-test npm test -- --coverage

after_success:
  - docker build -t suparera/multi-client ./client
  - docker build -t suparera/multi-nginx ./nginx
  - docker build -t suparera/multi-server ./server
  - docker build -t suparera/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push suparera/multi-client
  - docker push suparera/multi-nginx
  - docker push suparera/multi-server
  - docker push suparera/multi-worker

deploy:
  provider: elasticbeanstalk
  region: ap-southeast-1
  app: multi-docker
  env:  MultiDocker-env
  bucket_name: elasticbeanstalk-ap-southeast-1-303791465230
  bucket_path: docker_multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY